# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MistAir' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Auth'
	pod 'Charts'
	pod 'ChartsRealm'

  # Pods for MistAir

  target 'MistAirTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MistAirUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
